fix: 修复POST请求body为空时的签名错误
wechatpay-apiv3/wechatpay-postman-script pull request #15
Opened 2022-10-21 07:03 UTC by xy-peng

如题。

为了方便调试，增加了输出签名消息的日志。

2022-10-21 07:08 UTC, TheNorthMemory approved these changes

2022-10-21 08:08 UTC, EmmetZC requested changes

2022-10-21 08:08 UTC, EmmetZC commented on script.js
> +  body = typeof body === 'undefined' ? '' : body;
```suggestion
  body = body || '';
```

2022-10-21 08:25 UTC, TheNorthMemory commented on script.js
> +  body = typeof body === 'undefined' ? '' : body;
> body = body || '';
这个在 `false`, `null`, `0`, `0n` 等情形下，可能会不达预期，建议还是检查类型，明确`Undefined`类型时，置空值。

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/typeof

2022-10-21 13:21 UTC, xy-peng commented on script.js
> +  body = typeof body === 'undefined' ? '' : body;
集思广益，使用了 `requestBody.isEmpty()` 来判断 body 是否为空

2022-10-21 13:44 UTC, tpirc3 commented on script.js
> +if (pm.request.body.isEmpty() === false && (method === "POST" || method === "PUT" || method === "PATCH")) {
`!pm.request.body.isEmpty()` 会更好一些

2022-10-24 07:18 UTC, tpirc3 approved these changes

2022-10-24 08:39 UTC, EmmetZC approved these changes

2022-10-24 08:44 UTC, merged